// Enriched shared dataset of mock businesses/leads for development.
export const sampleBusinesses = [
  { 
    id: 101, 
    name: "Al-Rehman AC Repair", 
    city: "Karachi", 
    category: "HVAC & Repair", 
    website: "❌ No Website", 
    hasWebsite: false, 
    socialPresence: "FB Active (2022)", 
    emailStatus: "📧 Email Sent", 
    score: 88, 
    email: "info@alrehman-repair.pk", 
    websiteDetail: "Checked Tavily API: No dedicated domain found.", 
    socialDetail: "Facebook page found (last post Nov 2022).", 
    generatedVariation: "Assalam-o-Alaikum Al-Rehman Team...", 
    variationUsed: "Variation #2 (Roman Urdu - Service Offer)",
    date: "2026-08-03"
  },
  { 
    id: 102, 
    name: "Lumina Dynamics", 
    city: "Karachi", 
    category: "IT Services", 
    website: "✅ luminadynamics.com", 
    hasWebsite: true, 
    socialPresence: "FB & LinkedIn Active", 
    emailStatus: "⏭️ Skipped (Has Site)", 
    score: 15, 
    email: "contact@luminadynamics.com", 
    websiteDetail: "Website verified live.", 
    socialDetail: "Active footprint found.", 
    generatedVariation: "N/A — Qualified out.", 
    variationUsed: "None",
    date: "2026-08-02"
  },
  { 
    id: 103, 
    name: "Tariq Plumbing Experts", 
    city: "Lahore", 
    category: "Plumbing", 
    website: "❌ No Website", 
    hasWebsite: false, 
    socialPresence: "❌ None Found", 
    emailStatus: "🔥 Hot Lead", 
    score: 95, 
    email: "tariqplumbing.lhr@gmail.com", 
    websiteDetail: "No website found on Google.", 
    socialDetail: "Zero digital footprint found.", 
    generatedVariation: "AOA Tariq Sb, Lahore mein plumbing services...", 
    variationUsed: "Variation #1 (Roman Urdu - Direct Hook)",
    date: "2026-08-01"
  },
  { 
    id: 104, 
    name: "Vortex Systems", 
    city: "Islamabad", 
    category: "IT Services", 
    website: "❌ No Website", 
    hasWebsite: false, 
    socialPresence: "LinkedIn Active", 
    emailStatus: "📧 Email Sent", 
    score: 82, 
    email: "outreach@vortex.com.pk", 
    websiteDetail: "Domain vortex.com.pk is parked, no website.", 
    socialDetail: "LinkedIn company page with 5 employees.", 
    generatedVariation: "Hi Vortex Team, I noticed your website is parked...", 
    variationUsed: "Variation #3 (Professional - IT Audit)",
    date: "2026-08-03"
  },
  { 
    id: 105, 
    name: "Khyber Catering Services", 
    city: "Peshawar", 
    category: "Catering", 
    website: "✅ khybercatering.com", 
    hasWebsite: true, 
    socialPresence: "FB Active (2024)", 
    emailStatus: "⏭️ Skipped (Has Site)", 
    score: 22, 
    email: "contact@khybercatering.com", 
    websiteDetail: "Website live and active.", 
    socialDetail: "Facebook posting regularly.", 
    generatedVariation: "N/A — Qualified out.", 
    variationUsed: "None",
    date: "2026-08-02"
  },
  { 
    id: 106, 
    name: "Hassan Fashion & Retail", 
    city: "Karachi", 
    category: "Fashion & Retail", 
    website: "❌ No Website", 
    hasWebsite: false, 
    socialPresence: "Insta Active (10k followers)", 
    emailStatus: "🔥 Hot Lead", 
    score: 91, 
    email: "hassan.fashion.khi@gmail.com", 
    websiteDetail: "No website found. Selling exclusively on Instagram.", 
    socialDetail: "Highly active Instagram profile with 10k followers.", 
    generatedVariation: "AOA Hassan Team, loving your Insta collection! Have you thought about setting up a Shopify store...", 
    variationUsed: "Variation #4 (E-commerce Pitch)",
    date: "2026-08-03"
  }
];
