"use client";

import React, { useState } from "react";
import { 
  Search, 
  Download, 
  ChevronDown, 
  ChevronUp, 
  Mail, 
  CheckCircle2, 
  XCircle, 
  MessageSquare,
  Filter
} from "lucide-react";

interface Message {
  id: string;
  business: string;
  email: string;
  variation: number;
  subject: string;
  body: string;
  sentAt: string;
  status: "Delivered" | "Failed";
  reply: string;
}

const MOCK_MESSAGES: Message[] = [
  {
    id: "MSG-001",
    business: "Lumina Dynamics",
    email: "contact@luminadynamics.com",
    variation: 1,
    subject: "Quick question regarding Lumina Dynamics's digital setup",
    body: "Hi Lumina Dynamics team,\n\nWe noticed your online profile and wanted to reach out. Are you currently taking on new clients for software development?",
    sentAt: "2026-07-21 14:00",
    status: "Delivered",
    reply: "Yes, interested"
  },
  {
    id: "MSG-002",
    business: "Vortex Systems",
    email: "info@vortexsystems.io",
    variation: 2,
    subject: "Modernizing outreach for Vortex Systems",
    body: "Hello Vortex Systems,\n\nI was looking through Tech companies in Austin and saw your profile. Have you considered automating your client acquisition?",
    sentAt: "2026-07-21 13:30",
    status: "Delivered",
    reply: "No"
  },
  {
    id: "MSG-003",
    business: "Kinetica Co.",
    email: "sales@kinetica.com",
    variation: 1,
    subject: "Partnership opportunity",
    body: "Hi Kinetica Team,\n\nReaching out regarding your digital presence...",
    sentAt: "2026-07-21 12:15",
    status: "Failed",
    reply: "No"
  },
  {
    id: "MSG-004",
    business: "OmniCloud LLC",
    email: "hello@omnicloud.com",
    variation: 3,
    subject: "Streamlining client intake for OmniCloud LLC",
    body: "Dear OmniCloud team,\n\nWe love what you are building. We help businesses scale operations using AI agents.",
    sentAt: "2026-07-21 11:00",
    status: "Delivered",
    reply: "Tell me more"
  },
  {
    id: "MSG-005",
    business: "Solaris Peak",
    email: "support@solarispeak.com",
    variation: 2,
    subject: "Digital footprint inquiry for Solaris Peak",
    body: "Hi Solaris Peak,\n\nQuick thought on your current website and social channels...",
    sentAt: "2026-07-21 09:45",
    status: "Delivered",
    reply: "Call scheduled"
  }
];

export default function MessageLogPage() {
  const [messages] = useState<Message[]>(MOCK_MESSAGES);
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedStatus, setSelectedStatus] = useState<string>("ALL");
  const [selectedReply, setSelectedReply] = useState<string>("ALL");
  const [expandedId, setExpandedId] = useState<string | null>(null);

  // Toggle Row Expansion
  const toggleExpand = (id: string) => {
    setExpandedId(expandedId === id ? null : id);
  };

  // Filter Logic
  const filteredMessages = messages.filter((msg) => {
    const matchesSearch = 
      msg.business.toLowerCase().includes(searchQuery.toLowerCase()) ||
      msg.subject.toLowerCase().includes(searchQuery.toLowerCase()) ||
      msg.email.toLowerCase().includes(searchQuery.toLowerCase());

    const matchesStatus = 
      selectedStatus === "ALL" || msg.status === selectedStatus;

    const matchesReply = 
      selectedReply === "ALL" 
        ? true 
        : selectedReply === "REPLIED" 
        ? msg.reply !== "No" 
        : msg.reply === "No";

    return matchesSearch && matchesStatus && matchesReply;
  });

  // Export CSV Handler
  const exportCSV = () => {
    const headers = ["ID,Business,Email,Variation,Subject,Sent At,Status,Reply\n"];
    const rows = filteredMessages.map(
      (m) => `"${m.id}","${m.business}","${m.email}",${m.variation},"${m.subject}","${m.sentAt}","${m.status}","${m.reply}"`
    );
    const blob = new Blob([...headers, rows.join("\n")], { type: "text/csv" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `zara_message_log_${new Date().toISOString().split("T")[0]}.csv`;
    a.click();
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800 p-6 lg:p-8 space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-200 pb-5">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-violet-50 border border-violet-200 text-violet-600 shadow-sm">
            <Mail className="w-7 h-7" />
          </div>
          <div>
            <h1 className="text-2xl lg:text-3xl font-bold tracking-tight text-slate-900">
              Audit Message Log
            </h1>
            <p className="text-slate-500 text-sm mt-0.5">
              Audit trail of emails generated by Writer Agent and sent via Sender Agent (Gmail)
            </p>
          </div>
        </div>

        <button
          onClick={exportCSV}
          className="flex items-center justify-center gap-2 bg-violet-600 hover:bg-violet-700 text-white font-semibold px-4 py-2.5 rounded-lg shadow-sm hover:shadow transition-all text-sm"
        >
          <Download className="w-4 h-4" />
          Export CSV
        </button>
      </div>

      {/* Filters Bar */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
        {/* Search */}
        <div className="relative md:col-span-2">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
          <input
            type="text"
            placeholder="Search business, email, or subject..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-slate-50 border border-slate-200 focus:border-violet-500 focus:bg-white text-slate-800 text-sm rounded-lg pl-9 pr-4 py-2 outline-none transition-all"
          />
        </div>

        {/* Status Filter */}
        <div className="flex items-center gap-2">
          <Filter className="w-4 h-4 text-slate-400" />
          <select
            value={selectedStatus}
            onChange={(e) => setSelectedStatus(e.target.value)}
            className="w-full bg-slate-50 border border-slate-200 focus:border-violet-500 focus:bg-white text-slate-800 text-sm rounded-lg px-3 py-2 outline-none transition-all"
          >
            <option value="ALL">All Statuses</option>
            <option value="Delivered">Delivered</option>
            <option value="Failed">Failed</option>
          </select>
        </div>

        {/* Reply Filter */}
        <div className="flex items-center gap-2">
          <MessageSquare className="w-4 h-4 text-slate-400" />
          <select
            value={selectedReply}
            onChange={(e) => setSelectedReply(e.target.value)}
            className="w-full bg-slate-50 border border-slate-200 focus:border-violet-500 focus:bg-white text-slate-800 text-sm rounded-lg px-3 py-2 outline-none transition-all"
          >
            <option value="ALL">All Replies</option>
            <option value="REPLIED">Replied Only</option>
            <option value="NO_REPLY">No Reply</option>
          </select>
        </div>
      </div>

      {/* Messages Ledger Table */}
      <div className="bg-white border border-slate-200 rounded-xl overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm text-slate-700">
            <thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500 border-b border-slate-200">
              <tr>
                <th className="py-3.5 px-4 font-semibold">Business</th>
                <th className="py-3.5 px-4 font-semibold">Subject</th>
                <th className="py-3.5 px-4 font-semibold">Variation</th>
                <th className="py-3.5 px-4 font-semibold">Sent At</th>
                <th className="py-3.5 px-4 font-semibold">Status</th>
                <th className="py-3.5 px-4 font-semibold">Reply</th>
                <th className="py-3.5 px-4 text-right font-semibold">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredMessages.length === 0 ? (
                <tr>
                  <td colSpan={7} className="py-8 text-center text-slate-400">
                    No outbound messages found matching criteria.
                  </td>
                </tr>
              ) : (
                filteredMessages.map((msg) => (
                  <React.Fragment key={msg.id}>
                    <tr 
                      onClick={() => toggleExpand(msg.id)}
                      className="hover:bg-slate-50 cursor-pointer transition-colors"
                    >
                      <td className="py-3.5 px-4 font-semibold text-slate-900">
                        {msg.business}
                        <div className="text-xs font-normal text-slate-500">{msg.email}</div>
                      </td>
                      <td className="py-3.5 px-4 max-w-xs truncate text-slate-700">
                        {msg.subject}
                      </td>
                      <td className="py-3.5 px-4">
                        <span className="px-2.5 py-1 rounded-full text-xs font-mono font-semibold bg-violet-50 text-violet-700 border border-violet-200">
                          Var #{msg.variation}
                        </span>
                      </td>
                      <td className="py-3.5 px-4 text-xs text-slate-500 font-mono">
                        {msg.sentAt}
                      </td>
                      <td className="py-3.5 px-4">
                        {msg.status === "Delivered" ? (
                          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200">
                            <CheckCircle2 className="w-3.5 h-3.5" />
                            Delivered
                          </span>
                        ) : (
                          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold bg-red-50 text-red-700 border border-red-200">
                            <XCircle className="w-3.5 h-3.5" />
                            Failed
                          </span>
                        )}
                      </td>
                      <td className="py-3.5 px-4">
                        {msg.reply !== "No" ? (
                          <span className="px-2.5 py-1 rounded-full text-xs font-semibold bg-indigo-50 text-indigo-700 border border-indigo-200">
                            {msg.reply}
                          </span>
                        ) : (
                          <span className="text-xs text-slate-400 italic">No reply yet</span>
                        )}
                      </td>
                      <td className="py-3.5 px-4 text-right">
                        <button className="text-slate-400 hover:text-slate-600 transition-colors">
                          {expandedId === msg.id ? (
                            <ChevronUp className="w-5 h-5 inline" />
                          ) : (
                            <ChevronDown className="w-5 h-5 inline" />
                          )}
                        </button>
                      </td>
                    </tr>

                    {/* Expandable Body Drawer */}
                    {expandedId === msg.id && (
                      <tr className="bg-slate-50/70">
                        <td colSpan={7} className="p-4 border-l-4 border-violet-600">
                          <div className="space-y-2">
                            <div className="flex items-center justify-between text-xs text-slate-500 font-mono">
                              <span>MESSAGE ID: {msg.id}</span>
                              <span>TARGET: {msg.email}</span>
                            </div>
                            <div className="text-xs font-semibold text-violet-700 uppercase tracking-wider">
                              Subject: {msg.subject}
                            </div>
                            <div className="bg-white p-3.5 rounded-lg border border-slate-200 font-mono text-xs text-slate-800 whitespace-pre-wrap leading-relaxed shadow-sm">
                              {msg.body}
                            </div>
                          </div>
                        </td>
                      </tr>
                    )}
                  </React.Fragment>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}